services:
  - type: web
    name: ai-teacher-frontend
    env: node
    rootDir: frontend
    buildCommand: bash -c "npm install && npm run build"
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
